---

# All tasks about variables management

- name: 'INIT | VARIABLES | Check if OS family vars file exists'
  become: False
  stat:
    path: "{{ '{{ role_path }}/vars/os_family/{{ ansible_os_family | lower }}.yml' }}"
  register: '{{ cookiecutter.ansible_role_name | replace("-", "_") }}_check_os_family_vars'
  delegate_to: '127.0.0.1'


- name: 'INIT | VARIABLES | Check if OS distribution vars file exists'
  become: False
  stat:
    path: "{{ '{{ role_path }}/vars/os_distribution/{{ ansible_distribution | lower }}.yml' }}"
  register: '{{ cookiecutter.ansible_role_name | replace("-", "_") }}_check_os_distribution_vars'
  delegate_to: '127.0.0.1'


- name: 'INIT | VARIABLES | Check if OS release vars file exists'
  become: False
  stat:
    path: "{{ '{{ role_path }}/vars/os_distribution/{{ ansible_distribution | lower }}/{{ _os_release }}.yml' }}"
  register: '{{ cookiecutter.ansible_role_name | replace("-", "_") }}_check_os_release_vars'
  delegate_to: '127.0.0.1'
  vars:
    _os_release: "{{ '{{ (ansible_os_family | lower == \'redhat\') | ternary(ansible_distribution_major_version, (ansible_distribution_release | lower)) }}' }}"


- name: 'INIT | VARIABLES | Load OS family vars file'
  include_vars: "{{ '{{ ' ~ (cookiecutter.ansible_role_name | replace('-', '_')) ~ '_check_os_family_vars.stat.path }}' }}"
  when: "{{ (cookiecutter.ansible_role_name | replace('-', '_')) ~ '_check_os_family_vars.stat.exists' }}"


- name: 'INIT | VARIABLES | Load OS distribution vars file'
  include_vars: "{{ '{{ ' ~ (cookiecutter.ansible_role_name | replace('-', '_')) ~ '_check_os_distribution_vars.stat.path }}' }}"
  when: "{{ (cookiecutter.ansible_role_name | replace('-', '_')) ~ '_check_os_distribution_vars.stat.exists' }}"


- name: 'INIT | VARIABLES | Load OS release vars file'
  include_vars: "{{ '{{ ' ~ (cookiecutter.ansible_role_name | replace('-', '_')) ~ '_check_os_release_vars.stat.path }}' }}"
  when: "{{ (cookiecutter.ansible_role_name | replace('-', '_')) ~ '_check_os_release_vars.stat.exists' }}"
